### ISSUE TITLE
Default parsers not exported

### ISSUE THREAD

**Issue by adamAfro** [askonomm/marky#18]
So I wanted to use *marky* with some 👨🏼‍🏫*katex*, but the very first thing I came across is that `defaultParsers` are not exported ([see: marky.ts](https://github.com/askonomm/marky/blob/41de2a79901643d2d67e78a315338e873f81fbb1/marky.ts#L98-L103)), as it was [mentioned in the docs](https://github.com/askonomm/marky#extending-default-parsers):

> If you wish to add to the default parsers array, simply extend defaultParsers, like so:

```javascript
import { defaultParsers, marky } from "./marky.esm.js";
...
```

Not an issue for TS, as I can just *import* from `parser.ts`, but I code in JS, so here I am 🥸 

hoping I didn't miss something 😇

**Comment by askonomm** [comment]
Hey @adamAfro, sorry for the late reply. It's been awhile since I worked with Deno, but if I remember correctly the ESM file is generated by `deno bundle` command. So if you clone the repo and run `deno bundle marky.ts` it should create a JS file with all the things, so I'm actually surprised that it doesn't include a exporter `defaultParsers` given that it is actually exported in `parsers.ts` and, by my logic, should also be exported in the final bundle file. If not, seems it might be a bug with Deno itself.

**Comment by adamAfro** [comment]
No problemo for time @askonomm, thanks for response😁 
hi 👋

I did what u'd told me to, still - in output `defaultParsers` are just `const`:

```JS
const defaultParsers = [
...
];
export { marky as marky };
```

I tried with `parsers.ts` too and they're, as you'd told - all of them were exported.
Maybe it is something with how they are used in a file, or something, I don't know🤔

Adding `export { defaultParsers }` in `marky.ts` seems to fix the problem, tho
